
import java.awt.event.ActionEvent;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author depou
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        toComboBox = new javax.swing.JComboBox<>();
        fromComboBox = new javax.swing.JComboBox<>();
        inputField = new javax.swing.JTextField();
        output = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("INPUT");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("TO");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("FROM");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("RESULT");

        toComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EURO", "IDR" }));
        toComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toComboBoxActionPerformed(evt);
            }
        });

        fromComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IDR", "EURO", "USD" }));
        fromComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromComboBoxActionPerformed(evt);
            }
        });

        inputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFieldActionPerformed(evt);
            }
        });

        output.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        output.setFocusable(false);
        output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(toComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fromComboBox, 0, 305, Short.MAX_VALUE)
                                .addComponent(inputField)))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toComboBoxActionPerformed
        // TODO add your handling code here:
        try{
            String str = inputField.getText();
        double angka = Double.parseDouble(str);
        String kurs1 = fromComboBox.getSelectedItem().toString();
        String kurs2 = toComboBox.getSelectedItem().toString();
        String hasil = "";
        
        DecimalFormat df = new DecimalFormat("0.00");
        
        if(kurs1.equalsIgnoreCase("IDR")){
            if(kurs2.equalsIgnoreCase("USD")){
                hasil = "" + df.format(angka / 15670.0) + " $";
            }else if(kurs2.equalsIgnoreCase("EURO")){
                hasil = "" + df.format(angka / 16288.0) + " €";
            }else if (kurs2.equalsIgnoreCase("IDR")){
                hasil = "" + df.format(angka);
            };
            
        }else if(kurs1.equalsIgnoreCase("EURO")){
            if(kurs2.equalsIgnoreCase("IDR")){
                hasil = "" + df.format(angka * 16288.0);
            }else if(kurs2.equalsIgnoreCase("USD")){
                hasil = "" + df.format(angka * 1.04) + " $";
            }else if(kurs2.equalsIgnoreCase("EURO")){
                hasil = "" + df.format(angka) + " €";
            }
        
        }else if(kurs1.equalsIgnoreCase("USD")){
            if(kurs2.equalsIgnoreCase("IDR")){
                hasil = "" + df.format(angka * 15670.0);
            }else if(kurs2.equalsIgnoreCase("EURO")){
                hasil = "" + df.format(angka / 1.04) + " €";
            }else if(kurs2.equalsIgnoreCase("USD")){
                hasil = "" + df.format(angka) + " $";
            }
        
        };
        
        output.setText(hasil);
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Tolong Isi Input Dengan Angka",
               "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_toComboBoxActionPerformed

    private void fromComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromComboBoxActionPerformed
        // TODO add your handling code here:
        try{
            String str = inputField.getText();
        double angka = Double.parseDouble(str);
        String kurs1 = fromComboBox.getSelectedItem().toString();
        String kurs2 = toComboBox.getSelectedItem().toString();
        String hasil = "";
        
        DecimalFormat df = new DecimalFormat("0.00");
        
        if(kurs1.equalsIgnoreCase("IDR")){
            if(kurs2.equalsIgnoreCase("USD")){
                hasil = "" + df.format(angka / 15670.0) + " $";
            }else if(kurs2.equalsIgnoreCase("EURO")){
                hasil = "" + df.format(angka / 16288.0) + " €";
            }else if (kurs2.equalsIgnoreCase("IDR")){
                hasil = "" + df.format(angka);
            };
            
        }else if(kurs1.equalsIgnoreCase("EURO")){
            if(kurs2.equalsIgnoreCase("IDR")){
                hasil = "" + df.format(angka * 16288.0);
            }else if(kurs2.equalsIgnoreCase("USD")){
                hasil = "" + df.format(angka * 1.04) + " $";
            }else if(kurs2.equalsIgnoreCase("EURO")){
                hasil = "" + df.format(angka) + " €";
            }
        
        }else if(kurs1.equalsIgnoreCase("USD")){
            if(kurs2.equalsIgnoreCase("IDR")){
                hasil = "" + df.format(angka * 15670.0);
            }else if(kurs2.equalsIgnoreCase("EURO")){
                hasil = "" + df.format(angka / 1.04) + " €";
            }else if(kurs2.equalsIgnoreCase("USD")){
                hasil = "" + df.format(angka) + " $";
            }
        
        };
        
        output.setText(hasil);
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Tolong Isi Input Dengan Angka",
               "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_fromComboBoxActionPerformed

    private void inputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFieldActionPerformed
        // TODO add your handling code here:
        try{
            String str = inputField.getText();
        double angka = Double.parseDouble(str);
        String kurs1 = fromComboBox.getSelectedItem().toString();
        String kurs2 = toComboBox.getSelectedItem().toString();
        String hasil = "";
        
        DecimalFormat df = new DecimalFormat("0.00");
        
        if(kurs1.equalsIgnoreCase("IDR")){
            if(kurs2.equalsIgnoreCase("USD")){
                hasil = "" + df.format(angka / 15670.0) + " $";
            }else if(kurs2.equalsIgnoreCase("EURO")){
                hasil = "" + df.format(angka / 16288.0) + " €";
            }else if (kurs2.equalsIgnoreCase("IDR")){
                hasil = "" + df.format(angka);
            };
            
        }else if(kurs1.equalsIgnoreCase("EURO")){
            if(kurs2.equalsIgnoreCase("IDR")){
                hasil = "" + df.format(angka * 16288.0);
            }else if(kurs2.equalsIgnoreCase("USD")){
                hasil = "" + df.format(angka * 1.04) + " $";
            }else if(kurs2.equalsIgnoreCase("EURO")){
                hasil = "" + df.format(angka) + " €";
            }
        
        }else if(kurs1.equalsIgnoreCase("USD")){
            if(kurs2.equalsIgnoreCase("IDR")){
                hasil = "" + df.format(angka * 15670.0);
            }else if(kurs2.equalsIgnoreCase("EURO")){
                hasil = "" + df.format(angka / 1.04) + " €";
            }else if(kurs2.equalsIgnoreCase("USD")){
                hasil = "" + df.format(angka) + " $";
            }
        
        };
        
        output.setText(hasil);
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Tolong Isi Input Dengan Angka",
               "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_inputFieldActionPerformed

    private void outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> fromComboBox;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField output;
    private javax.swing.JComboBox<String> toComboBox;
    // End of variables declaration//GEN-END:variables
}
